import { Row } from "./type";

export const rows: Row[] = [
  {
    idInvoice: 1,
    date: "2024-07-01",
    name: "John Doe",
    email: "john.doe@example.com",
    serviceType: "Consulting",
    status: "Pending",
  },
  {
    idInvoice: 2,
    date: "2024-07-02",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    serviceType: "Development",
    status: "Complete",
  },
  {
    idInvoice: 3,
    date: "2024-07-03",
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    serviceType: "Design",
    status: "Pending",
  },
  {
    idInvoice: 4,
    date: "2024-07-04",
    name: "Alice Brown",
    email: "alice.brown@example.com",
    serviceType: "Marketing",
    status: "Cancel",
  },
  {
    idInvoice: 5,
    date: "2024-07-05",
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    serviceType: "Support",
    status: "Pending",
  },
  {
    idInvoice: 6,
    date: "2024-07-06",
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    serviceType: "Consulting",
    status: "Complete",
  },
  {
    idInvoice: 7,
    date: "2024-07-07",
    name: "David Martinez",
    email: "david.martinez@example.com",
    serviceType: "Development",
    status: "Pending",
  },
  {
    idInvoice: 8,
    date: "2024-07-08",
    name: "Sophia Anderson",
    email: "sophia.anderson@example.com",
    serviceType: "Design",
    status: "Cancel",
  },
  {
    idInvoice: 9,
    date: "2024-07-09",
    name: "James Lee",
    email: "james.lee@example.com",
    serviceType: "Marketing",
    status: "Complete",
  },
];
